function [ best, fit, avg  ] = pf_ga_gene_summary( sorted_psp, fit_psp )
%PF_GA_GENE_SUMMARY Summary of this function goes here
%   Detailed explanation goes here


    %% best values
    best = [ ...
            fit_psp(1).cost, ...
            fit_psp(1).ele_cost, ...
            fit_psp(1).sp.tan_eta_tol, ...
            fit_psp(1).sp.tan_vel_tol, ...
            fit_psp(1).sp.obs_power, ...
            fit_psp(1).sp.obs_wall, ...
            fit_psp(1).sp.dmp_dist_stop, ...
            fit_psp(1).sp.dmp_ang_stop, ...
            fit_psp(1).sp.gain_tangent, ...
            fit_psp(1).sp.gain_risk, ...
            fit_psp(1).sp.att_force_max_sat, ...
            fit_psp(1).sp.att_force_min_sat, ...
           ];
       
    %% fittest of the latest generation
    fit = [ ...
            sorted_psp(1).cost, ...
            sorted_psp(1).ele_cost, ...
            sorted_psp(1).sp.tan_eta_tol, ...
            sorted_psp(1).sp.tan_vel_tol, ...
            sorted_psp(1).sp.obs_power, ...
            sorted_psp(1).sp.obs_wall, ...
            sorted_psp(1).sp.dmp_dist_stop, ...
            sorted_psp(1).sp.dmp_ang_stop, ...
            sorted_psp(1).sp.gain_tangent, ...
            sorted_psp(1).sp.gain_risk, ...
            sorted_psp(1).sp.att_force_max_sat, ...
            sorted_psp(1).sp.att_force_min_sat, ...
           ];

    %% Average of latest generation
    % number of parameters
    num_param = length(fit);
    
    % calculate averages
    avg = zeros(1,num_param);
    for i = sorted_psp
        avg = avg + [ ...
                        i.cost, ...
                        i.ele_cost, ...
                        i.sp.tan_eta_tol, ...
                        i.sp.tan_vel_tol, ...
                        i.sp.obs_power, ...
                        i.sp.obs_wall, ...
                        i.sp.dmp_dist_stop, ...
                        i.sp.dmp_ang_stop, ...
                        i.sp.gain_tangent, ...
                        i.sp.gain_risk, ...
                        i.sp.att_force_max_sat, ...
                        i.sp.att_force_min_sat, ...
                    ];
    end
    avg = avg / length(sorted_psp);

end

