function pf_plot_costs( iter_costs )
%PF_PLOT_COSTS Summary of this function goes here
%   Detailed explanation goes here

    len_costs = length(iter_costs(:,1));
    if length(iter_costs(:,1)) > 1
        plot( ...
            1:len_costs, iter_costs(:,1), 'k', ...
            1:len_costs, iter_costs(:,2), 'r', ...
            1:len_costs, iter_costs(:,3), 'g', ...
            1:len_costs, iter_costs(:,4), 'b', ...
            1:len_costs, iter_costs(:,5), 'c' ...
            );
%         fmt_title = '%-6s Cost ( %6.3f )';
%         titles = [ ...
%             sprintf(fmt_title, 'Total',     iter_costs(end,1)); ...
%             sprintf(fmt_title, 'Turn',      iter_costs(end,2)); ...
%             sprintf(fmt_title, 'Length',    iter_costs(end,3)); ...
%             sprintf(fmt_title, 'Time',      iter_costs(end,4)); ...
%             sprintf(fmt_title, 'Range',     iter_costs(end,5))  ...
%             ];
%         legend( titles(1,:), titles(2,:), titles(3,:), titles(4,:), titles(5,:),  'Location', 'NorthWest' );
    end

end

